# Generated by Django 4.0.4 on 2022-08-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMSAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Student_number',
            new_name='student_number',
        ),
    ]
